name: Deploy to Heroku

on:
  push:
    branches:
      - main # Déclenche l'action lors d'un push sur la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag Docker image
        run: |
          docker build . -t registry.heroku.com/ynov-api-yohan/web

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku container registry
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      - name: Push Docker image to Heroku container registry
        run: |
          docker push registry.heroku.com/ynov-api-yohan/web

      - name: Release the app on Heroku
        run: |
          heroku container:release web -a ynov-api-yohan
